// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmmXDS2UyjoI_zF5wiuk_dPAQ9OBrBs0c',
    appId: '1:1083632235464:web:4b307b261b89d8862ec6fd',
    messagingSenderId: '1083632235464',
    projectId: 'cuisinegenie-1bdf3',
    authDomain: 'cuisinegenie-1bdf3.firebaseapp.com',
    storageBucket: 'cuisinegenie-1bdf3.appspot.com',
    measurementId: 'G-H087938QLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtdRbMpenZV8xCvhKKQv_-DIO_Yfy5KqA',
    appId: '1:1083632235464:android:2806c5ddf826a5342ec6fd',
    messagingSenderId: '1083632235464',
    projectId: 'cuisinegenie-1bdf3',
    storageBucket: 'cuisinegenie-1bdf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCifUUpDmbT85KKdZweVc9cK8fRGsb9iG0',
    appId: '1:1083632235464:ios:2d23a72d72f28d452ec6fd',
    messagingSenderId: '1083632235464',
    projectId: 'cuisinegenie-1bdf3',
    storageBucket: 'cuisinegenie-1bdf3.appspot.com',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCifUUpDmbT85KKdZweVc9cK8fRGsb9iG0',
    appId: '1:1083632235464:ios:2d23a72d72f28d452ec6fd',
    messagingSenderId: '1083632235464',
    projectId: 'cuisinegenie-1bdf3',
    storageBucket: 'cuisinegenie-1bdf3.appspot.com',
    iosBundleId: 'com.example.cookbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmmXDS2UyjoI_zF5wiuk_dPAQ9OBrBs0c',
    appId: '1:1083632235464:web:ea1de2579be7f1b22ec6fd',
    messagingSenderId: '1083632235464',
    projectId: 'cuisinegenie-1bdf3',
    authDomain: 'cuisinegenie-1bdf3.firebaseapp.com',
    storageBucket: 'cuisinegenie-1bdf3.appspot.com',
    measurementId: 'G-4Y4JC9XLPK',
  );
}
